language: python

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
      - pandoc

python:
  - "2.7"
  - "3.4"

install:
  - pip install -r requirements-dev.txt
  - pip install coveralls
  - python setup.py install

script:
  - python setup.py test
  - find . -type f -name "*.py" | xargs flake8

after_success:
  - python setup.py --long-description | rst2html5.py
  - coverage run --source=pyoscar -m unittest pyoscar.tests.run_tests
  - coverage report -m
  - coveralls
  - python setup.py sdist bdist_wheel --universal
